name: "Jan-Willem van de Meent"
url: "https://jwvdm.github.io"
permalink: /:year/:month/:day/:title
timezone: Europe/Amsterdam

navigation:
- text: Home
  url: /
# Hidden for now
# - text: Talks
#   url: /talks/
- text: Publications
  url: /publications/

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography
